version: "3.9"
services:
  mongodb-band:
    container_name: mongodb-band
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-band-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27001:27017"
    restart: on-failure:10

  mongodb-disc:
    container_name: mongodb-disc
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-disc-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27002:27017"
    restart: on-failure:10

  mongodb-genre:
    container_name: mongodb-genre
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-genre-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27003:27017"
    restart: on-failure:10

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  mongodb-band-data:
  mongodb-disc-data:
  mongodb-genre-data:
