version: "3.9"
services:
  mongodb-band:
    container_name: mongodb-band
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-band-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27001:27017"
    restart: on-failure:10

  mongodb-disc:
    container_name: mongodb-disc
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-disc-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27002:27017"
    restart: on-failure:10

  mongodb-genre:
    container_name: mongodb-genre
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-genre-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27003:27017"
    restart: on-failure:10
    
  mongodb-customer:
    container_name: mongodb-customer
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-customer-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27004:27017"
    restart: on-failure:10
    
  mongodb-order:
    container_name: mongodb-order
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-order-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27005:27017"
    restart: on-failure:10
    
  mongodb-payment:
    container_name: mongodb-payment
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-payment-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27006:27017"
    restart: on-failure:10

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
      
  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    container_name: zookeeper-2
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181

  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongodb-band-data:
  mongodb-disc-data:
  mongodb-genre-data:
  mongodb-customer-data:
  mongodb-order-data:
  mongodb-payment-data:
