server:
  port: ${PORT:${SERVER_PORT:0}}
  #forward-headers-strategy: framework 
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  data:
    mongodb:
      host: localhost
      port: 27001
      database: band
  application:
    zipkin: http://localhost:9411
      
resilience4j:
  circuitbreaker:
    instances:
        discCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        genreCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
  retry:
    instances:
      discCB:
        maxRetryAttempts: 3
        waitDuration: 10s
              
springdoc:
  swagger-ui:
    path: /band/swagger-ui.html
  api-docs:
    path: /band/v3/api-docs
  packagesToScan: com.band.service.controller
  
logging:
  file:
    name: logstash/elk-stack.log
    path: C:/Users/esu99pitrive/Desktop/developer/msproject/logstash/