server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  client:
    service-url:
      default-zone: http://eureka-service:8761/eureka

spring:
  application:
    name: band-service
  cloud:
    config:
      enabled: true
      uri: http://config-service:8888
  data:
    mongodb:
      host: mongodb-band
      port: 27001
      database: band
  spring:
    zipkin:
      base-url: http://zipkin:9411