server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    service-url:
      default-zone: http://eureka-service:8761/eureka

spring:
  application:
    name: genre-service
  cloud:
    config:
      enabled: true
      uri: http://config-service:8000
  data:
    mongodb:
      host: mongodb-genre
      port: 27003
      database: genre
  spring:
    zipkin:
      base-url: http://zipkin:9411