server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  data:
    mongodb:
      host: localhost
      port: 27005
      database: order
  application:
    zipkin: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      group-id: group-default #group-id that will ne used by default   
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.order"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    
springdoc:
  swagger-ui:
    path: /order/swagger-ui.html
  api-docs:
    path: /order/v3/api-docs
  packagesToScan: com.order.service.controller