version: "3.9"
services:
  mongodb-band:
    container_name: mongodb-band
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-band-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27001:27017"
    restart: on-failure:10

  mongodb-disc:
    container_name: mongodb-disc
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-disc-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27002:27017"
    restart: on-failure:10

  mongodb-genre:
    container_name: mongodb-genre
    image: bitnami/mongodb:4.0.27
    volumes:
      - mongodb-genre-data:/bitnami/mongodb/data
      - ../../mongodb/mongodump:/mongodump
    ports:
      - "27003:27017"
    restart: on-failure:10

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  config-service:
    image: piterrivero/config-service:latest
    container_name: config-service
    ports:
      - "8888:8888"

  eureka-service:
    image: piterrivero/eureka-service:latest
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config-service
      - zipkin
      
  gateway-service:
    image: piterrivero/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - config-service
      - zipkin
      - eureka-service    
      
  band-service:
    image: piterrivero/band-service:latest
    container_name: band-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb-band
      - config-service 
      - zipkin
      - eureka-service
      - gateway-service
      
  disc-service:
    image: piterrivero/disc-service:latest
    container_name: disc-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb-disc
      - config-service
      - zipkin
      - eureka-service
      - gateway-service
      
  genre-service:
    image: piterrivero/genre-service:latest
    container_name: genre-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb-genre
      - config-service
      - zipkin
      - eureka-service
      - gateway-service

volumes:
  mongodb-band-data:
  mongodb-disc-data:
  mongodb-genre-data:
