version: "3.9"
services:

  config-service:
    image: piterrivero/config-service:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - msproject
        
  eureka-server-service:
    image: piterrivero/eureka-service:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    container_name: eureka-server-sevice
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    networks:
      - msproject
    
  gateway-service:
    image: piterrivero/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - config-service
      - eureka-server-service
    networks:
      - msproject    
      
#  band-service:
#    image: piterrivero/band-service:latest
#    container_name: band-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - config-service 
#      - eureka-service
#      - gateway-service
#    networks:
#      - services
#      
#  disc-service:
#    image: piterrivero/disc-service:latest
#    container_name: disc-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - config-service
#      - eureka-service
#      - gateway-service
#    networks:
#      - services
#      
#  genre-service:
#    image: piterrivero/genre-service:latest
#    container_name: genre-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - config-service
#      - eureka-service
#      - gateway-service
#    networks:
#      - services
  
networks:
  msproject:
    external: true
